[package]
name = "indexer"
version = "0.1.0"
authors = ["walt <walton.l.seymour@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"